### ISSUE TITLE
Crash while generating world with OTG

### ISSUE THREAD

**Issue by m-vlad** [valeriotor/Beyond-The-Veil#2]
For context, I've tried generating the world with the Dregora preset.

Here's the crash log:
```---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (ForgeEndertech-1.12.2-4.5.1.0-build.0454.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  AALoadingPlugin (arcanearchives-0.2.0.17.jar)
  midnight (themidnight-0.3.5.jar)
  OTGCorePlugin (OTG-Core.jar)
  AstralCore (astralsorcery-1.12.2-1.10.23.jar)
  HCASM (HammerLib-1.12.2-2.0.6.14.jar)
  PerformantLoadingPlugin (performant-1.12.2-1.9.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.10-core.jar)
  McLib core mod (mclib-1.0.4-1.12.2.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Quark Plugin (Quark-r1.6-178.jar)
  iceandfire (iceandfire-1.8.4.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  CharmLoadingPlugin (Charm-1.12.2-1.3.6.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 4/8/20 8:01 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.valeriotor.beyondtheveil.research.ResearchUtil.isResearchComplete(ResearchUtil.java:89)
	at com.valeriotor.beyondtheveil.events.MemoryUnlocks.boneMealEvent(MemoryUnlocks.java:162)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1407_MemoryUnlocks_boneMealEvent_BonemealEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onApplyBonemeal(ForgeEventFactory.java:455)
	at net.minecraft.item.ItemDye.applyBonemeal(ItemDye.java:111)
	at net.minecraft.item.ItemDye.func_179234_a(ItemDye.java:103)
	at vazkii.quark.world.world.underground.UndergroundBiomeLush.finalFloorPass(UndergroundBiomeLush.java:28)
	at vazkii.quark.world.world.UndergroundBiomeGenerator.lambda$apply$1(UndergroundBiomeGenerator.java:91)
	at vazkii.quark.world.world.UndergroundBiomeGenerator$$Lambda$3283/99916477.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at vazkii.quark.world.world.UndergroundBiomeGenerator.apply(UndergroundBiomeGenerator.java:91)
	at vazkii.quark.world.world.UndergroundBiomeGenerator.generateChunkPart(UndergroundBiomeGenerator.java:41)
	at vazkii.quark.world.world.MultiChunkFeatureGenerator.generate(MultiChunkFeatureGenerator.java:33)
	at vazkii.quark.world.feature.UndergroundBiomes.onOreGenerate(UndergroundBiomes.java:248)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1122_UndergroundBiomes_onOreGenerate_GenerateMinable.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.terraingen.TerrainGen.generateOre(TerrainGen.java:101)
	at com.pg85.otg.forge.events.ForgeEventHandler.onResourceProcess(ForgeEventHandler.java:86)
	at com.pg85.otg.OTGEngine.fireResourceProcessEvent(OTGEngine.java:211)
	at com.pg85.otg.OTG.fireResourceProcessEvent(OTG.java:265)
	at com.pg85.otg.generator.resource.Resource.process(Resource.java:143)
	at com.pg85.otg.generator.ObjectSpawner.populate(ObjectSpawner.java:251)
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185931_b(OTGChunkGenerator.java:257)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:210)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1444485072 bytes (1377 MB) / 5136973824 bytes (4899 MB) up to 8405385216 bytes (8016 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9017m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 128 mods loaded, 127 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version                  | Source                                           | Signature                                |
	|:------ |:-------------------------------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2                   | minecraft.jar                                    | None                                     |
	| LCHIJA | mcp                                          | 9.42                     | minecraft.jar                                    | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                    | None                                     |
	| LCHIJA | forge                                        | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                    | None                                     |
	| LCHIJA | ivtoolkit                                    | 1.3.3-1.12               | minecraft.jar                                    | None                                     |
	| LCHIJA | otgcore                                      | 1.12.2 - v8.3            | minecraft.jar                                    | None                                     |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                          | minecraft.jar                                    | None                                     |
	| LCHIJA | jei                                          | 4.15.0.291               | jei_1.12.2-4.15.0.291.jar                        | None                                     |
	| LCHIJA | abyssalcraft                                 | 1.9.18                   | AbyssalCraft-1.12.2-1.9.18.jar                   | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | mantle                                       | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                         | None                                     |
	| LCHIJA | quark                                        | r1.6-178                 | Quark-r1.6-178.jar                               | None                                     |
	| LCHIJA | ctm                                          | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                        | None                                     |
	| LCHIJA | baubles                                      | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCHIJA | thaumcraft                                   | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                 | None                                     |
	| LCHIJA | twilightforest                               | 3.10.1013                | twilightforest-1.12.2-3.10.1013-universal.jar    | None                                     |
	| LCHIJA | tconstruct                                   | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                 | None                                     |
	| LCHIJA | acintegration                                | 1.10.0                   | AbyssalCraft Integration-1.12.2-1.10.0.jar       | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | forgeendertech                               | 1.12.2-4.5.1.0           | ForgeEndertech-1.12.2-4.5.1.0-build.0454.jar     | None                                     |
	| LCHIJA | adhooks                                      | 1.12.2-3.2.3.0           | AdHooks-1.12.2-3.2.3.0-build.0435.jar            | None                                     |
	| LCHIJA | orbis-lib                                    | 0.2.0                    | orbis-lib-1.12.2-0.2.0+build224.jar              | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA | aether                                       | 0.2.7                    | aether_ii-1.12.2-0.2.7+build224-universal.jar    | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA | akashictome                                  | 1.2-12                   | AkashicTome-1.2-12.jar                           | None                                     |
	| LCHIJA | alcatrazcore                                 | 1.0.4                    | alcatrazcore-1.0.4.jar                           | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCHIJA | antiqueatlas                                 | 4.6.3                    | antiqueatlas-1.12.2-4.6.3.jar                    | None                                     |
	| LCHIJA | antiqueatlasoverlay                          | 1.2                      | antiqueatlas-1.12.2-4.6.3.jar                    | None                                     |
	| LCHIJA | applecore                                    | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                     | None                                     |
	| LCHIJA | appleskin                                    | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                       | None                                     |
	| LCHIJA | ebwizardry                                   | 4.2.10                   | ElectroblobsWizardry-4.2.10-MC1.12.2.jar         | None                                     |
	| LCHIJA | arcane_essentials                            | 1.0                      | Arcane Essentials-1.0.0-alpha-6.jar              | None                                     |
	| LCHIJA | gbook_snapshot                               | 2.9.1.s5                 | Guidebook-1.12.2-2.9.1.s5.jar                    | None                                     |
	| LCHIJA | arcanearchives                               | 0.2.0.17                 | arcanearchives-0.2.0.17.jar                      | None                                     |
	| LCHIJA | conarm                                       | 1.2.5.4                  | conarm-1.12.2-1.2.5.4.jar                        | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | armoryexpansion                              | 1.4.1                    | armoryexpansion-1.4.1.jar                        | None                                     |
	| LCHIJA | armoryexpansion-custommaterials              | 1.4.1                    | armoryexpansion-1.4.1.jar                        | None                                     |
	| LCHIJA | llibrary                                     | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                       | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | iceandfire                                   | 1.8.4                    | iceandfire-1.8.4.jar                             | None                                     |
	| LCHIJA | armoryexpansion-iceandfire                   | 1.4.1                    | armoryexpansion-1.4.1.jar                        | None                                     |
	| LCHIJA | armoryexpansion-matteroverdrive              | 1.4.1                    | armoryexpansion-1.4.1.jar                        | None                                     |
	| LCHIJA | astralsorcery                                | 1.10.22                  | astralsorcery-1.12.2-1.10.23.jar                 | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | waystones                                    | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                       | None                                     |
	| LCHIJA | atlasextras                                  | 1.7                      | AtlasExtras-1.12.2-1.7.jar                       | None                                     |
	| LCHIJA | autoreglib                                   | 1.3-32                   | AutoRegLib-1.3-32.jar                            | None                                     |
	| LCHIJA | bettercaves                                  | 1.12.2                   | bettercaves-1.12.2-1.6.0.jar                     | None                                     |
	| LCHIJA | beyondtheveil                                | 1.12.2-0.1               | BeyondTheVeil-1.12.2-0.1.jar                     | None                                     |
	| LCHIJA | cg                                           | 1.0                      | cg_1.12-1.0.jar                                  | None                                     |
	| LCHIJA | mclib                                        | 1.0.4                    | mclib-1.0.4-1.12.2.jar                           | None                                     |
	| LCHIJA | metamorph                                    | 1.2                      | changeling-1.2-1.12.2_command-fixes.jar          | None                                     |
	| LCHIJA | charm                                        | 1.12.2-1.3.6             | Charm-1.12.2-1.3.6.jar                           | None                                     |
	| LCHIJA | clumps                                       | 3.1.2                    | Clumps-3.1.2.jar                                 | None                                     |
	| LCHIJA | morpheus                                     | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                      | None                                     |
	| LCHIJA | comforts                                     | 1.4.1.3                  | comforts-1.12.2-1.4.1.3.jar                      | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
	| LCHIJA | controlling                                  | 3.0.8                    | Controlling-3.0.8.jar                            | None                                     |
	| LCHIJA | corpse                                       | 1.12.2-1.0.6             | corpse-1.12.2-1.0.6.jar                          | None                                     |
	| LCHIJA | craftstudioapi                               | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar            | None                                     |
	| LCHIJA | defiledlands                                 | 1.4.3                    | defiledlands-1.12.2-1.4.3.jar                    | None                                     |
	| LCHIJA | dimdoors                                     | 3.0.9+287                | DimensionalDoors-3.0.9-287.jar                   | None                                     |
	| LCHIJA | doubledoors                                  | 1.2                      | doubledoors_1.12-1.2.jar                         | None                                     |
	| LCHIJA | openterraingenerator                         | v8.3                     | OpenTerrainGenerator-1.12.2 - v8.3.jar           | None                                     |
	| LCHIJA | dregora                                      | 1.0                      | Dregora-1.12.2-v1.65 Biome+ Part1.jar            | None                                     |
	| LCHIJA | dynamictrees                                 | 1.12.2-0.9.7             | DynamicTrees-1.12.2-0.9.7.jar                    | None                                     |
	| LCHIJA | dynamictreestc                               | 1.12.2-1.4.1e            | DynamicTreesTC-1.12.2-1.4.1e.jar                 | None                                     |
	| LCHIJA | ebp                                          | 1.0                      | ebp_1.12-1.0.jar                                 | None                                     |
	| LCHIJA | ediblegs                                     | 1.0                      | ediblegs_1.12-1.0.jar                            | None                                     |
	| LCHIJA | es                                           | 2.0                      | edibsgr_1.12-2.0.jar                             | None                                     |
	| LCHIJA | endreborn                                    | 0.3.3                    | EndReborn III [0.3.3].jar                        | None                                     |
	| LCHIJA | enhancedarmaments                            | 1.3.19                   | enhancedarmaments-1.3.19.jar                     | None                                     |
	| LCHIJA | extrabows                                    | v1.12.2 b12              | extrabows-v1.12.2 b12.jar                        | None                                     |
	| LCHIJA | extra_spells                                 | 1.1.4                    | ExtraSpells-1.12.2-1.1.4.jar                     | None                                     |
	| LCHIJA | fastleafdecay                                | v14                      | FastLeafDecay-v14.jar                            | None                                     |
	| LCHIJA | forgelin                                     | 1.8.4                    | Forgelin-1.8.4.jar                               | None                                     |
	| LCHIJA | gottschcore                                  | 1.12.1                   | GottschCore-mc1.12.2-f14.23.5.2768-v1.12.1.jar   | None                                     |
	| LCHIJA | overlord                                     | 2.4.14                   | Overlord-1.12.2-2.4.14.jar                       | None                                     |
	| LCHIJA | guideapi                                     | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                      | None                                     |
	| LCHIJA | hammercore                                   | 2.0.6.14                 | HammerLib-1.12.2-2.0.6.14.jar                    | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | healthhungertweaks                           | 2.1.1                    | healthhungertweaks-1.12-2.1.1.jar                | None                                     |
	| LCHIJA | howlingmoon                                  | 0.9                      | howlingmoon-1.12.2-0.9.jar                       | None                                     |
	| LCHIJA | waila                                        | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                      | None                                     |
	| LCHIJA | ichunutil                                    | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | improvableskills                             | 65r                      | ImprovableSkills-1.12.2-65r.jar                  | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCHIJA | inventorypets                                | 2.0.4                    | inventorypets-1.12-2.0.4.jar                     | None                                     |
	| LCHIJA | inventorytweaks                              | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | jeresources                                  | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar          | None                                     |
	| LCHIJA | keywizard                                    | 1.12.2-1.7.3             | keywizard-1.12.2-1.7.3.jar                       | None                                     |
	| LCHIJA | mm                                           | 0.3.4                    | Maelstrom Mod-0.3.4.jar                          | None                                     |
	| LCHIJA | moarboats                                    | 4.1.2.1                  | moarboats-1.12.2-4.1.2.1.jar                     | None                                     |
	| LCHIJA | modnametooltip                               | 1.10.1                   | modnametooltip_1.12.2-1.10.1.jar                 | None                                     |
	| LCHIJA | mousetweaks                                  | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                    | None                                     |
	| LCHIJA | movingworld                                  | 1.12-6.342               | movingworld-1.12-6.342-full.jar                  | None                                     |
	| LCHIJA | naturescompass                               | 1.8.5                    | NaturesCompass-1.12.2-1.8.5.jar                  | None                                     |
	| LCHIJA | notreepunching                               | 2.0.20                   | notreepunching-2.0.20.jar                        | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCHIJA | patchouli                                    | 1.0-20                   | Patchouli-1.0-20.jar                             | None                                     |
	| LCHIJA | performant                                   | 1.12.2-1.4               | performant-1.12.2-1.9.jar                        | None                                     |
	| LCHIJA | pirates                                      | 0.0.6                    | pirates-0.0.6B.jar                               | None                                     |
	| LCHIJA | plustic                                      | 8.0.0.1                  | plustic-8.0.0.1.jar                              | None                                     |
	| LCHIJA | pvj                                          | 1.6.4                    | ProjectVibrantJourneys-1.12.2-1.6.4.jar          | None                                     |
	| LCHIJA | raiders                                      | 3.0.9                    | raiders-1.12.2-3.0.9.jar                         | None                                     |
	| LCHIJA | additionalstructures                         | 2.3.1                    | Rex's-Additional-Structures-1.12.x-(v.2.3.1).jar | None                                     |
	| LCHIJA | savemystronghold                             | 1.12.2-1.0.0             | savemystronghold-1.12.2-1.0.0.jar                | None                                     |
	| LCHIJA | scalingfeast                                 | v1.1.2-beta              | scalingfeast-1.1.2-beta.jar                      | None                                     |
	| LCHIJA | sereneseasons                                | 1.2.18                   | SereneSeasons-1.12.2-1.2.18-universal.jar        | None                                     |
	| LCHIJA | skeletonhs                                   | 1.1                      | skeletonhs_1.12-1.1.jar                          | None                                     |
	| LCHIJA | smooth-scrolling-everywhere                  | 1.1                      | smooth-scrolling-everywhere-1.1.jar              | None                                     |
	| LCHIJA | soulboundarmory                              | 2.5.1                    | soulboundarmory-2.5.1.jar                        | None                                     |
	| LCHIJA | stg                                          | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                             | None                                     |
	| LCHIJA | tektopia                                     | 1.1.0                    | tektopia-1.1.0.jar                               | None                                     |
	| LCHIJA | tektopiainformation                          | 1.4.0                    | TektopiaInformation-1.12.2-1.1.0-1.4.0.jar       | None                                     |
	| LCHIJA | tfspellpack                                  | 1.0                      | TFSpellPack-1.0-MC1.12.2.jar                     | None                                     |
	| LCHIJA | tcinventoryscan                              | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar       | None                                     |
	| LCHIJA | thaumicjei                                   | 1.6.0                    | ThaumicJEI-1.12.2-1.6.0-27.jar                   | None                                     |
	| LCHIJA | thaumictinkerer                              | 1.12.2-5.0-353c71c       | thaumictinkerer-1.12.2-5.0-353c71c.jar           | None                                     |
	| LCHIJA | thaumicwaila                                 | 1.12.2-0.0.2             | ThaumicWaila-1.12.2-0.0.2.jar                    | None                                     |
	| LCHIJA | tinkertoolleveling                           | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar              | None                                     |
	| LCHIJA | treasure2                                    | 1.10.0                   | Treasure2-mc1.12.2-f14.23.5.2768-v1.10.0.jar     | None                                     |
	| LCHIJA | xat                                          | 0.29.2                   | Trinkets and Baubles-1.12.2-0.29.2.jar           | None                                     |
	| LCHIJA | vamparasol                                   | 0.0.4                    | Vamparasol_0.0.4.jar                             | None                                     |
	| LCHIJA | vampirism                                    | 1.6.2                    | Vampirism-1.12.2-1.6.2.jar                       | None                                     |
	| LCHIJA | teamlapen-lib                                | 1.6.2                    | Vampirism-1.12.2-1.6.2.jar                       | None                                     |
	| LCHIJA | vampirism_integrations                       | vampirism_integrations   | VampirismIntegrations-1.12.2-1.2.0.jar           | None                                     |
	| LCHIJA | vanillavistas                                | 1.0                      | Vanilla_Vistas 1.1.jar                           | None                                     |
	| LCHIJA | wailaharvestability                          | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar            | None                                     |
	| LCHIJA | wawla                                        | 2.6.275                  | Wawla-1.12.2-2.6.275.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | phosphor-lighting                            | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50.jar                | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCHIJA | reauth                                       | 3.6.0                    | reauth-3.6.0.jar                                 | daba0ec4df71b6da841768c49fb873def208a1e3 |
	| LCHIJA | thebetweenlands                              | 3.5.10                   | TheBetweenlands-3.5.10-universal.jar             | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LCHIJA | midnight                                     | 0.3.5                    | themidnight-0.3.5.jar                            | None                                     |
	| LCHIJA | armoryexpansion-conarm                       | 1.4.1                    | armoryexpansion-1.4.1.jar                        | None                                     |
	| LCHIJA | mysticallib                                  | 1.12.2-1.7.0             | mysticallib-1.12.2-1.7.0.jar                     | None                                     |
	| UD     | mclib_core                                   | 1.0.4                    | minecraft.jar                                    | None                                     |

	Loaded coremods (and transformers): 
CorePlugin (ForgeEndertech-1.12.2-4.5.1.0-build.0454.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
ForgelinPlugin (Forgelin-1.8.4.jar)
  
AALoadingPlugin (arcanearchives-0.2.0.17.jar)
  
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
AstralCore (astralsorcery-1.12.2-1.10.23.jar)
  
HCASM (HammerLib-1.12.2-2.0.6.14.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
PerformantLoadingPlugin (performant-1.12.2-1.9.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.10-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
McLib core mod (mclib-1.0.4-1.12.2.jar)
  mchorse.mclib.core.McLibCMClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Quark Plugin (Quark-r1.6-178.jar)
  vazkii.quark.base.asm.ClassTransformer
iceandfire (iceandfire-1.8.4.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
CharmLoadingPlugin (Charm-1.12.2-1.3.6.jar)
  svenhjol.charm.base.CharmClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)
		- quarkIntegration (Enabled/Not Forced)

	HammerCore Debug Information: 
Dependent Mods:
    -Improvable Skills (improvableskills) @65r

	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 425.54
	OpenGlRenderer: GeForce RTX 2060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12```

**Comment by valeriotor** [comment]
Thanks, this was a very important report. While I wasn't able to reproduce it myself I am fairly certain of what and where the problem is, and it's something I've got to keep into account now in multiple places.
I had done little testing with other mods so this was very appreciated, I'll probably roll out a patch in the following days and see if it fixes it.

**Comment by valeriotor** [comment]
Just uploaded v0.1.1 on Curseforge, that should _hopefully_ fix the issue. Whenever you have the time you could try again.

**Comment by m-vlad** [comment]
Thanks, that solved it.
